In [1]:
import pandas as pd

In [2]:
file_path = "/Volumes/Engineering/Database/HMCorp/java/train.jsonl"
hmcorp = pd.read_json(file_path, lines=True)

In [ ]:
srcml = pd.read_csv("../scg_features.csv").sample(10)

In [ ]:
srcml["label"] = 1 - srcml["label"]
srcml.head()

,filename,index,label,num_nodes,num_edges,num_self_loops,graph_density,num_cycles,sum_degree,avg_degree,max_degree,min_degree,median_degree,avg_in_degree,avg_out_degree
95904,gj074081_ai.xml,74081,0,61,110,11,0.030055,50,242,3.967213,13,1,3.0,1.983607,1.983607
204871,gj157837_human.xml,157837,1,100,188,14,0.018990,89,404,4.040000,10,1,4.0,2.020000,2.020000
182160,gj140798_ai.xml,140798,0,68,123,12,0.026997,56,270,3.970588,10,1,3.0,1.985294,1.985294
75993,gj058332_ai.xml,58332,0,72,136,14,0.026604,65,300,4.166667,13,1,4.0,2.083333,2.083333
30013,gj022746_ai.xml,22746,0,158,308,34,0.012416,151,684,4.329114,15,1,4.0,2.164557,2.164557

In [8]:
srcml["id"] =  srcml["filename"].str.split("_").str[0]
srcml.head()

,filename,index,label,num_nodes,num_edges,num_self_loops,graph_density,num_cycles,sum_degree,avg_degree,max_degree,min_degree,median_degree,avg_in_degree,avg_out_degree,id
95904,gj074081_ai.xml,74081,0,61,110,11,0.030055,50,242,3.967213,13,1,3.0,1.983607,1.983607,gj074081
204871,gj157837_human.xml,157837,1,100,188,14,0.018990,89,404,4.040000,10,1,4.0,2.020000,2.020000,gj157837
182160,gj140798_ai.xml,140798,0,68,123,12,0.026997,56,270,3.970588,10,1,3.0,1.985294,1.985294,gj140798
75993,gj058332_ai.xml,58332,0,72,136,14,0.026604,65,300,4.166667,13,1,4.0,2.083333,2.083333,gj058332
30013,gj022746_ai.xml,22746,0,158,308,34,0.012416,151,684,4.329114,15,1,4.0,2.164557,2.164557,gj022746